version: '2'
services:

    mysql:
        image: mysql:5.6
        container_name: mysql_5_6
        ports:
        - 3306:3306
        restart: always
        volumes:
        - ./mysql/initdb:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
        - ./mysql/tmp:/var/tmp
        environment:
        - MYSQL_ROOT_PASSWORD=pass1234
        - MYSQL_DATABASE=admin_atgwp
        - MYSQL_USER=admin_atgwp
        - MYSQL_PASSWORD=pass1234

    php:
        build: ./php
        container_name: php_5_5
        restart: always
        ports:
        - '80:80'
        volumes:
        - ./www/html:/var/www/html
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin 
        container_name: phpmyadmin
        ports: 
        - 81:80
        environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql_5_6
        depends_on:
        - mysql
        restart: always
        